name: 'AWS CloudFormation Stack status checker for GitHub Action'
description: 'Retrives the AWS CloudFormation Stack status'
author: 'Kenji Saito'
inputs:
  stack-name:
    required: true
    description: 'The name of AWS CloudFormation Stack to be status checked.'
  region:
    required: false
    description: 'The region of AWS CloudFormation Stack to be status checked.'
outputs:
  status:
    description: 'The status of AWS CloudFormation Stack.'
runs:
  using: 'node16'
  main: 'dist/index.mjs'
