packages:
  - .
  - test

allowBuilds:
  unrs-resolver: false

enablePrePostScripts: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - aws-cdk-lib@2.260.0
  - brace-expansion@5.0.8

overrides:
  aws-cdk-lib@<2.260.0: ^2.260.0
  brace-expansion@<=5.0.7: ^5.0.8

strictPeerDependencies: false
