packages:
  - .
  - test

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - fast-xml-parser@5.7.1
  - fast-xml-builder@1.1.5
  - uuid@14.0.0

overrides:
  fast-xml-parser@<5.7.0: '>=5.7.0'

strictPeerDependencies: false
