packages:
  - .
  - test

allowBuilds:
  unrs-resolver: false

enablePrePostScripts: false

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - pnpm@11.9.0

overrides:
  fast-xml-parser@<5.7.0: '>=5.7.0'

  '@types/node': ^24

strictPeerDependencies: false
